# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02323a5070d7fd06a85e52b92ba2415159e6edfd0145a5bdce928e0d3172a7bf83337d0bf43af0dcf890fb1a2a6b781c9957d9cc66f4f702484c03c50c3e294

test:
  secret_key_base: c49a7e407cc8c23cd2ffa9e35f4e7d7bc03d7ea48fe44a3aa10009a41a90bde6942c176eee8a78389a50229653c616ab04dd3468502e268c66a2b74fe0a05176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
